[versions]
geary = "0.18.106"
guiy = "0.6.21"

[libraries]
protocolburrito = "com.mineinabyss:protocolburrito:0.4.33"
geary-papermc-core = { module = "com.mineinabyss:geary-papermc-core", version.ref = "geary" }
guiy = { module = "com.mineinabyss:guiy-compose", version.ref = "guiy" }
